const TRANSLATIONS = {
    no: {
        // Toolbar
        toolbar_home: 'Hjem',
        toolbar_save: 'Lagre',
        toolbar_forms: 'Lagret',
        toolbar_export: 'Eksport',
        toolbar_service: 'Lageruttak',
        toolbar_settings: 'Meny',
        toolbar_timebok: 'Timebok',
        timebok_title: 'Timebok',
        timebok_add_day: '+ Ny dag',
        timebok_add_line: '+ Legg til linje',
        timebok_sum_hours: 'Totale timer',
        timebok_sum_wage: 'Totallønn',
        timebok_sum_travel: 'Reisegodtgjørelse',
        timebok_sum_days: 'Dager ført',
        timebok_summary_title: 'Ukesammendrag',
        timebok_summary_title_month: 'Månedssammendrag',
        timebok_today: 'I dag',
        timebok_no_entries: 'Ingen registreringer',
        timebok_line_one: 'linje',
        timebok_line_many: 'linjer',
        timebok_calc_with: 'Beregnet med',
        timebok_per_hour: 'pr. time',
        timebok_rates_unset: 'Satser ikke satt – fyll inn i Innstillinger',
        timebok_day_travel: 'Reisegodtgjørelse',
        timebok_pick_project: 'Velg prosjekt',
        timebok_pick_type: 'Velg kode',
        timebok_new_project: '+ Legg til',
        timebok_new_project_title: 'Nytt prosjekt',
        timebok_search_project: 'Søk prosjekt …',
        timebok_no_project_matches: 'Ingen treff',
        timebok_no_projects: 'Ingen prosjekter ennå.',
        timebok_delete_day_confirm: 'Slette denne dagen?',
        timebok_sum_receipts: 'Kvitteringer',
        timebok_sum_total: 'Sum',
        timebok_project: 'Prosjekt',
        timebok_no_project: 'Ingen prosjekt',
        timebok_code_hint: 'Legg til en tilleggskode med timer/beløp',
        timebok_codes: 'Tilleggskoder',
        timebok_add_code: '+ Legg til kode',
        timebok_add_project: '+ Legg til prosjekt',
        timebok_receipts: 'Kvitteringer',
        timebok_add_receipt: '+ Legg til kvittering',
        timebok_receipt_label_ph: 'Beskrivelse',
        timebok_day_totals: 'Dagens totaler',
        timebok_d_hours: 'Timer',
        timebok_d_wage: 'Lønn',
        timebok_d_travel: 'Reise',
        timebok_d_receipts: 'Kvitteringer',
        timebok_saved: 'Alt er lagret',
        timebok_saving: 'Lagrer …',
        timebok_menu_today: 'Gå til i dag',
        timebok_menu_settings: 'Innstillinger',
        timebok_sync_projects: 'Hent fra Prosjekter & lager',
        timebok_projects_added: 'prosjekter lagt til',
        timebok_projects_none_new: 'Ingen nye prosjekter',
        settings_timebok: 'Timebok',
        settings_timebok_timesats: 'Timesats',
        settings_timebok_timetypes: 'Tidstyper',
        settings_timebok_brackets: 'Reise-tillegg (avstand)',
        settings_timebok_projects: 'Prosjekter',
        btn_mark_sent: 'Merk sendt',
        btn_mark_ferdig: 'Merk godkjent',
        btn_mark_ikke_godkjent: 'Merk ikke godkjent',
        form_mark_btn: 'Merk som',
        mark_sent_confirm: 'Merk dette skjemaet som sendt?',
        mark_ferdig_confirm: 'Merk dette skjemaet som ferdig (signert)?',
        marked_as_ferdig: 'Skjema markert som godkjent!',
        marked_as_ikke_godkjent: 'Skjema markert som ikke godkjent!',

        // Login
        login: 'Logg inn',
        logout: 'Logg ut',
        logout_confirm: 'Vil du logge ut?',
        logout_success: 'Du er nå logget ut',
        login_success: 'Logget inn som ',
        login_failed: 'Innlogging feilet: ',
        login_choose_provider: 'Velg innloggingsmetode',
        login_google: 'Logg inn med Google',
        login_microsoft: 'Logg inn med Microsoft',
        firebase_not_configured: 'Firebase er ikke konfigurert. Sjekk firebaseConfig i script.js',

        // Loading
        generating_file: 'Genererer fil...',

        // Sent banner
        sent_banner_text: 'Dette skjemaet er sendt',
        sent_banner_hint: 'Trykk «Lagre» for å flytte til lagrede skjemaer',
        sent_banner_move: 'Flytt til lagrede',

        // Mobile form header
        form_subtitle: 'Ordreseddel',
        beta_label: 'Beta',

        // Field labels
        label_ordreseddel_nr: 'Ordreseddel nr.',
        label_uke: 'Uke',
        label_montor: 'Montør',
        label_avdeling: 'Avdeling',
        label_oppdragsgiver: 'Oppdragsgiver',
        label_kundens_ref: 'Kundens ref.',
        label_fakturaadresse: 'Fakturaadresse',
        label_prosjektnr: 'Prosjektnr.',
        label_prosjektnavn: 'Prosjektnavn',
        label_sted: 'Sted',
        label_dato: 'Dato',
        label_kundens_underskrift: 'Kundens underskrift',
        signature_tap_to_sign: 'Trykk for å signere',
        signature_not_signed: 'Ikke signert',
        signature_title: 'Signer her',
        signature_clear: 'Slett signatur',
        signature_clear_short: 'Slett',
        signature_confirm: 'Bekreft',

        // Sections
        section_work: 'Utførte arbeider',
        section_signing: 'Signering',

        // Order cards
        order_description: 'Beskrivelse',
        order_title: 'Bestilling',
        timer_chip_label: 'Timer ført',
        timer_week_label: 'Timer uke',
        timer_week_this: '(denne)',
        timer_week_total: 'Sum uke',
        timer_day_total: 'Sum dag',
        timer_week_no_uke: 'Sett uke for å se ukens timer.',
        timer_overview_title: 'Denne ordreseddelen',
        timer_overview_total: 'Sum ordreseddel',
        timer_overview_empty: 'Ingen bestillinger ennå',
        timer_overview_other: 'Annet',
        timer_overview_no_hours: 'Ingen timer ført',
        order_materials_label: 'Materialer',
        order_add_material: 'Materialer',
        order_edit_material: 'Endre materialer',
        material_isolation: 'Isolasjon',
        material_kappe: 'Isolering',
        order_days: 'Arbeidstid',
        order_skip_materialer: 'Ingen materialer for denne bestillingen',
        order_skipped_materialer: 'Ingen materialer',
        order_skip_arbeidstid: 'Ingen arbeidstid for denne bestillingen',
        order_skipped_arbeidstid: 'Ingen arbeidstid',
        btn_undo: 'Angre',
        order_merknad: 'Merknad',
        order_merknad_placeholder: 'Valgfri merknad...',
        order_plan: 'Plan',
        order_plan_placeholder: 'Etasje(r)...',
        order_add: '+ Legg til bestilling',
        order_delete_confirm: 'Slett denne bestillingen?',
        picker_delete_confirm: 'Slett denne raden?',

        // Material placeholders
        placeholder_material: 'Materiale',
        placeholder_quantity: 'Antall',
        placeholder_unit: 'Enhet',

        // Save menu
        save_menu_title: 'Lagre skjema',
        save_option: 'Lagre',
        save_as_template: 'Lagre som prosjekt',

        // Save confirmations
        confirm_save: 'Er du sikker på at du vil lagre skjemaet?',
        confirm_update: 'Dette ordrenummeret finnes allerede. Vil du oppdatere det?',
        confirm_move_to_saved: 'Vil du flytte denne ordreseddelen tilbake til lagrede?',
        save_success: 'Skjema lagret!',
        update_success: 'Skjema oppdatert!',
        save_error: 'Feil ved lagring: ',
        duplicate_in_sent: 'Ordreseddel nr. {0} finnes allerede i sendte.',
        btn_save: 'Lagre',
        btn_update: 'Oppdater',

        // Export menu
        export_title: 'Eksporter som',
        export_only_label: 'Kun eksporter',
        export_and_mark_label: 'Marker som sendt',
        btn_cancel: 'Avbryt',
        btn_clear: 'Fjern',
        btn_preview: 'Vis',
        btn_close: 'Lukk',
        btn_back: 'Tilbake',
        btn_sign: 'Signer',
        btn_done: 'Ferdig',
        btn_signed: 'Signert',
        duplicate_btn: 'Dupliser',
        copy_btn: 'Kopier',
        edit_btn: 'Rediger',
        delete_btn: 'Slett',
        more_actions: 'Handlinger',
        export_pdf_error: 'Feil ved generering av PDF: ',
        export_png_error: 'Feil ved generering av PNG: ',
        btn_share: 'Del',
        share_error: 'Feil ved deling: ',
        share_ready_prompt: 'Filen er klar. Trykk Del for å åpne delings-menyen.',
        share_not_supported: 'Deling støttes ikke i denne nettleseren. Bruk Chrome eller en mobil nettleser.',
        export_download: 'Last ned',
        btn_select: 'Velg',
        btn_download: 'Last ned',
        btn_export_ellipsis: 'Eksporter…',
        btn_select_all: 'Velg alle',
        btn_deselect_all: 'Fjern alle',
        bulk_count_suffix: 'valgt',
        bulk_mark_as: 'Merk som:',
        bulk_mark_btn: 'Merk som',
        status_lagret: 'Lagret',
        status_sendt: 'Sendt',
        status_ferdig: 'Godkjent',
        status_ikke_godkjent: 'Ikke godkjent',
        bulk_mark_confirm: 'Sette {0} skjema til «{1}»?',
        bulk_marked: '{0} skjema satt til «{1}»',
        select_mode_title: 'Velg skjemaer',
        bulk_export_title: 'Eksporter valgte',
        bulk_mark_sent_label: 'Marker alle som ferdig',
        bulk_section_combined_pdf: 'Samlet PDF (1 fil)',
        bulk_section_separate_pdf: 'Separate PDF-filer',
        bulk_section_separate_png: 'Separate PNG-filer',
        bulk_combine_pdf_label: 'Samle alle PDF-er til én fil',

        // Hent modal
        modal_load_title: 'Skjemaer',
        tab_own: 'Ordreseddel',
        search_placeholder: 'Søk ordre-/prosjektnr eller prosjektnavn...',
        search_template_placeholder: 'Søk prosjekt...',
        loading: 'Laster...',
        no_saved_forms: 'Ingen lagrede skjemaer',
        no_templates: 'Ingen prosjekter',
        load_more: 'Last flere',

        // List items
        no_name: 'Uten navn',

        // Form actions
        delete_confirm: 'Er du sikker på at du vil slette dette skjemaet?',
        delete_sent_confirm: 'Er du sikker på at du vil slette dette skjemaet permanent?',
        move_to_saved_confirm: 'Vil du flytte dette skjemaet til lagrede?',
        move_to_saved_success: 'Skjema flyttet til lagrede!',
        marked_as_sent: 'Skjema markert som sendt!',
        btn_ferdig: 'Marker som ferdig',
        btn_move: 'Flytt',
        duplicate_confirm: 'Vil du duplisere dette skjemaet?',
        duplicated_success: 'Skjema duplisert — husk å lagre!',
        copied_to_clipboard: 'Kopiert!',

        // New form
        new_form_confirm: 'Vil du starte et nytt skjema? Ulagrede endringer vil gå tapt.',
        btn_start_new: 'Start ny',
        unsaved_warning: 'Du har ulagrede endringer. Vil du fortsette?',
        btn_continue: 'Fortsett',

        // Templates (a "template" in this app = a saved project)
        template_modal_title: 'Velg prosjekt',
        template_section_title: 'Prosjekter',
        template_new_form: 'Eget skjema',
        template_blank_form: '+ Ordreseddel',
        template_save_success: 'Prosjekt lagret!',
        template_duplicated: 'Prosjekt duplisert — rediger og lagre!',
        template_update_success: 'Prosjekt oppdatert!',
        template_exists: 'Et prosjekt med prosjektnavn «{0}» finnes allerede. Vil du oppdatere det?',
        template_name_required: 'Du må fylle inn prosjektnavn for å lagre prosjektet',
        template_save_error: 'Feil ved lagring av prosjekt: ',
        template_delete_confirm: 'Er du sikker på at du vil slette dette prosjektet?',

        // Settings
        settings_title: 'Innstillinger',
        settings_ordrenr: 'Ordreseddelnummer',
        settings_defaults: 'Autofyll',
        settings_min_info: 'Min info',
        settings_min_info_navn: 'Navn',
        settings_min_info_fornavn: 'Fornavn',
        settings_min_info_etternavn: 'Etternavn',
        signature_rotate_device: 'Snu enheten til landscape',
        settings_min_info_mobil: 'Mobil',
        settings_min_info_epost: 'E-post',
        settings_min_info_section_personalia: 'Personalia',
        settings_min_info_section_defaults: 'Standardverdier',
        settings_min_info_default_leveringsadresse: 'Standard leveringsadresse (kappeskjema)',
        settings_min_info_uke_hint: 'Settes til denne ukes nummer',
        settings_min_info_dato_hint: 'Settes til dagens dato',
        settings_section_autofyll: 'Autofyll',
        settings_section_required: 'Obligatoriske felt',
        settings_section_skjemaer: 'Skjemaer',
        settings_section_global: 'Generelt',
        settings_fields: 'Feltinnstillinger',
        settings_new_template: '+ Nytt prosjekt',
        settings_edit_template: 'Rediger prosjekt',
        settings_template_deactivate: 'Deaktiver',
        settings_template_activate: 'Aktiver',
        settings_template_inactive: '(deaktivert)',
        no_templates_settings: 'Ingen prosjekter',
        template_updated: 'Prosjekt oppdatert!',
        settings_language: 'Språk',
        settings_saved: 'Innstillinger lagret!',
        settings_add_range: 'Legg til minst ett nummerområde.',
        settings_range_error: '"Fra" må være mindre enn eller lik "Til".',
        settings_range_overlap: 'Området overlapper med et eksisterende nummerområde.',
        settings_range_added: 'Nummerområde lagt til!',
        settings_range_remove: 'Fjerne nummerområde {0} – {1}?',
        settings_no_ranges: 'Ingen nummerområder lagt til',
        settings_used: 'Brukt: {0} av {1}',
        settings_next: 'Neste: {0}',
        settings_all_used: 'Alle brukt!',
        ordrenr_remaining: '{0} ledige',
        ordrenr_remaining_empty: 'Tom for nummer – be sjefen om nye',
        settings_my_numbers: 'Mine numre',
        settings_given_away: 'Gitt bort',
        settings_given_away_count: 'Gitt bort: {0}',
        settings_give_btn: 'Gi bort',
        settings_give_added: 'Numre markert som gitt bort!',
        settings_give_remove: 'Få tilbake «{0}»?',
        settings_give_not_in_range: 'Numrene må være innenfor et registrert nummerområde.',
        settings_give_overlap: 'Overlapper med numre som allerede er gitt bort.',
        settings_give_already_used: 'Nummer {0} er allerede brukt i en ordreseddel.',
        settings_defaults_saved: 'Standardverdier lagret!',
        settings_values_header: 'Verdier',
        settings_autofill_header: 'Automatisk utfylling',
        placeholder_from: 'Fra',
        placeholder_to: 'Til',
        btn_save_settings: 'Lagre',
        btn_add: 'Legg til',

        // Plan settings
        settings_plans: 'Plan / Etasjer',
        settings_plan_add: '+ Legg til etasje',
        settings_plan_placeholder: 'Etasjenavn...',
        settings_plan_exists: 'Denne etasjen finnes allerede',
        settings_plan_remove: 'Fjerne "{0}"?',
        settings_plan_edit_title: 'Rediger etasjenavn:',
        settings_no_plans: 'Ingen etasjer lagt til',
        plan_picker_title: 'Velg plan',

        // Materials & units settings
        settings_materials: 'Materialer',
        settings_materials_list: 'Materialer',
        settings_units_list: 'Enheter',
        material_type_standard: 'Standard',
        material_type_mansjett: 'Mansjett',
        material_type_brannpakning: 'Brannpakning',
        material_type_kabelhylse: 'Kabelhylse',
        material_type_standard_desc: 'Standard — antall + enhet',
        material_type_mansjett_desc: 'Mansjett — bredde/Ø, høyde',
        material_type_brannpakning_desc: 'Brannpakning — bredde/Ø, høyde, runder',
        material_type_kabelhylse_desc: 'Kabelhylse — bredde/Ø, høyde, dybde',
        placeholder_new_material: 'Nytt materiale',
        placeholder_new_material_required: 'Nytt materiale *',
        placeholder_new_unit: 'Ny enhet',
        placeholder_gate: 'Gateadresse',
        placeholder_postnr: 'Postnr.',
        placeholder_postnr_poststed: 'Postnr. / Poststed',
        placeholder_poststed: 'Poststed',
        placeholder_fakturaadresse: 'Trykk for å fylle ut',
        settings_material_added: 'Materiale lagt til!',
        settings_unit_added: 'Enhet lagt til!',
        settings_material_exists: 'Dette materialet finnes allerede.',
        settings_unit_exists: 'Denne enheten finnes allerede.',
        settings_material_remove: 'Fjerne «{0}»?',
        settings_no_materials: 'Ingen materialer lagt til',
        settings_no_units: 'Ingen enheter lagt til',
        picker_custom: 'Egendefinert',
        picker_add: 'Legg til',
        picker_ok: 'Ok',
        picker_incomplete: '{0} mangler antall eller enhet.',
        picker_search_placeholder: 'Søk eller legg til materiale...',
        settings_spec_toggle: 'Trenger mål (diameter/dimensjoner)',
        settings_lm_toggle: 'Beregn løpemeter',
        settings_default_unit: 'Standard enhet',
        dim_popup_diameter_placeholder: 'Diameter (mm)',
        dim_popup_width_placeholder: 'Bredde / Diameter (mm)',
        dim_popup_height_placeholder: 'Høyde (mm) — valgfri',
        dim_popup_depth_placeholder: 'Dybde (mm)',
        dim_popup_generic_placeholder: 'Bredde / Diameter (mm)',
        dim_popup_length_placeholder: 'Lengde (mm) \u2014 valgfri',
        dim_popup_rounds_placeholder: 'Runder',
        dim_popup_title_diameter: 'diameter (mm)',
        dim_popup_title_dimensions: 'mål (mm)',
        dim_invalid_diameter: 'Vennligst oppgi et gyldig mål',
        material_exists: 'Materialet finnes allerede',

        // Required fields settings
        settings_required: 'Krav ved lagring og eksport',
        settings_tpl_required: 'Obligatoriske felt',
        settings_req_save: 'Lagre / Eksport',
        settings_req_template: 'Prosjekt',
        settings_req_beskrivelse: 'Beskrivelse (minst 1 ordre)',
        settings_req_etasjer: 'Etasjer',
        validation_kundens_ref: 'Kundens ref.',
        validation_fakturaadresse: 'Fakturaadresse',
        validation_signatur: 'Kundens underskrift',

        // Language page
        lang_norwegian: 'Norsk',
        lang_english: 'English',

        // Validation
        required_field: 'Du må fylle inn {0}',
        validation_day_missing_etasje: '{0} mangler etasje. Når en dag har timer, må også etasje fylles ut.',
        validation_day_missing_timer: '{0} mangler timer. Når en dag har etasje, må også timer fylles ut.',
        validation_etasje_required: 'Fyll inn minst én etasje når det er ført timer.',
        required_order: 'Du må legge til minst én bestilling',
        required_description: 'Beskrivelse mangler for bestilling {0}',
        validation_ordreseddel_nr: 'Ordreseddel nr.',
        validation_dato: 'Dato',
        validation_oppdragsgiver: 'Oppdragsgiver',
        validation_prosjektnr: 'Prosjektnr.',
        validation_prosjektnavn: 'Prosjektnavn',
        validation_montor: 'Montør',
        validation_avdeling: 'Avdeling',
        validation_sted: 'Sted',
        validation_signering_dato: 'Signering dato',

        // Confirm modal defaults
        confirm_default: 'Er du sikker?',
        btn_remove: 'Fjern',

        form_title: 'Ordreseddel',

        // Desktop export labels (used in buildDesktopWorkLines)
        export_materials: 'Materiell:',
        export_hours: 'Timer:',
        export_hours_unit: 'timer',
        export_total: 'Totalt:',

        // Service (Lageruttak — uttak-modus i Servicebil)
        tab_service: 'Lageruttak',
        service_title: 'Lageruttak Servicebiler',
        service_new_form: '+ Lageruttak',
        servicebil_title: 'Servicebil',
        servicebil_inntak: 'Inntak',
        servicebil_uttak: 'Uttak',
        servicebil_inntak_title: 'Materialer inn i bil',
        servicebil_inntak_no_materials: 'Du må legge til minst ett materiale',
        service_entries_title: 'Prosjekter',
        service_add_entry: '+ Legg til prosjekt',
        service_entry_title: 'Prosjekt',
        service_entry_delete_confirm: 'Slett dette prosjektet?',
        service_save_success: 'Lageruttak lagret!',
        service_no_saved: 'Ingen lagrede lageruttak',
        service_montor_required: 'Du må fylle inn montør',
        service_label_signatur: 'Signatur',
        template_pick: 'Velg prosjekt',
        template_picker_title: 'Prosjekter',
        no_templates: 'Ingen prosjekter',

        // Kappeskjema
        kappe_new_form: '+ Kappeskjema',
        kappe_title: 'Kappeskjema',
        tab_kappe: 'Kappeskjema',
        tab_servicebil: 'Servicebil',
        kappe_section_project: 'Prosjekt',
        kappe_section_delivery: 'Leveringsadresse',
        kappe_section_customer: 'Kunde og faktura',
        tpl_levering_same_as_faktura: 'Bruk fakturaadresse',
        tpl_levering_use_faktura: 'Bruk fakturaadresse',
        fak_use_fakturaadresse: 'Bruk fakturaadresse',
        fak_use_leveringsadresse: 'Bruk leveringsadresse',
        tpl_default_leveringsadresse: 'Default leveringsadresse (kappeskjema)',
        tpl_default_leveringsadresse_none: 'Ingen',
        settings_leveringsadresser: 'Leveringsadresser',
        settings_templates_and_addresses: 'Prosjekter & lager',
        settings_prosjekter_section: 'Prosjekter',
        settings_lager_section: 'Lager',
        lager_use: 'Bruk lager',
        lager_not_set: 'Ingen lager satt opp. Gå til Innstillinger → Prosjekter & lager.',
        prosjekt_leveringsadresse_pick: 'Bruk prosjekt',
        prosjekt_leveringsadresse_pick_title: 'Velg prosjekt',
        no_prosjekt_leveringsadresser: 'Ingen prosjekter med leveringsadresse',
        settings_new_leveringsadresse: '+ Ny adresse',
        settings_edit_leveringsadresse: 'Rediger adresse',
        settings_leveringsadresse_navn: 'Navn',
        no_leveringsadresser: 'Ingen lagrede leveringsadresser',
        leveringsadresse_pick: 'Velg leveringsadresse',
        leveringsadresse_pick_title: 'Velg leveringsadresse',
        confirm_delete_leveringsadresse: 'Slette leveringsadressen?',
        kappe_section_products: 'Kappeliste',
        kappe_section_staples: 'Stift',
        kappe_section_fasteners: 'Festemidler',
        kappe_label_nr: 'Kappenr.',
        kappe_label_dato: 'Dato',
        kappe_label_onsket_leveringsdato: 'Ønsket leveringsdato',
        kappe_label_bestiller: 'Bestiller',
        kappe_label_mottaker: 'Mottaker',
        kappe_label_veiadresse: 'Gateadresse',
        kappe_label_kontakt: 'Kontakt',
        kappe_label_tlf: 'Tlf.',
        kappe_label_pallemerking: 'Pallemerking',
        kappe_col_produkt: 'Produkt',
        kappe_col_bredde: 'Bredde',
        kappe_col_lopemeter: 'LM',
        kappe_col_antall: 'Antall',
        kappe_col_antall_sider: 'Sider',
        kappe_lm_title: 'Løpemeter',
        kappe_add_lengde: 'Legg til lengde',
        kappe_add_rad: 'Legg til rad',
        kappe_lm_empty: 'Legg til lengder nedenfor.',
        kappe_lm_sum: 'Sum',
        kappe_lengder_badge: 'lengder',
        kappe_steel: 'Stål',
        kappe_steel_new: 'Nytt stål',
        kappe_add_steel: 'Legg til stål',
        kappe_maal_title: 'Mål',
        kappe_col_maal: 'Mål',
        kappe_add_maal: 'Legg til mål',
        kappe_maal_empty: 'Skriv inn ett eller flere mål.',
        iso_bredde: 'Bredde',
        iso_add_row: 'Legg til rad',
        iso_lm_per_side: 'LM',
        iso_antall_objekter: 'Antall',
        iso_sider: 'Sider',
        iso_mode_bredde: 'Stk',
        iso_mode_plate: 'Plate',
        iso_plate_count: 'Antall plater',
        kappe_unit_stk: 'Stk',
        kappe_unit_eske: 'Eske',
        kappe_col_kappelengde: 'Kappelengde',
        kappe_add_line: '+ Legg til produkt',
        kappe_line_title: 'Produkt',
        kappe_line_delete_confirm: 'Slett denne kappelinjen?',
        kappe_steel_delete_confirm: 'Slette dette stålet og alle lengdene i det?',
        kappe_duplicate_line: 'Dupliser produkt',
        kappe_add_kapp: 'Legg til stk',
        iso_add_group: 'Legg til gruppe',
        iso_add_section: 'Legg til seksjon',
        iso_group_name_ph: 'Gruppe',
        iso_btn_stk: 'Stk',
        iso_btn_plate: 'Plate',
        iso_btn_section: 'Seksjon',
        iso_length_title: 'LM og antall',
        iso_length_add: 'legg til',
        btn_ok: 'OK',
        iso_add_product: 'Legg til isolasjonsprodukt',
        kappe_add_product: '+ Legg til gruppe',
        kappe_add_plate_product: '+ Plate-linje',
        kappe_add_plate: 'Legg til plate',
        kappe_add_fastener: 'Legg til festemiddel',
        fastener_choose_product: 'Velg produkt',
        fastener_edit: 'Endre festemidler',
        iso_edit_products: 'Endre produkter',
        fastener_add_dimension: 'Legg til dimensjon',
        kappe_add_fast_stk: 'Legg til stk',
        kappe_add_fast_eske: 'Legg til eske',
        kappe_pick_product_hint: 'Velg produkt for å legge til rader',
        kappe_kapp_section: 'Kapp',
        kappe_plate_section: 'Hele plater',
        kappe_line_plate_delete_confirm: 'Slett denne plate-linjen?',
        kappe_col_merknad: 'Merknad',
        kappe_plate_length: 'Platelengde (mm)',
        kappe_plate_width: 'Platebredde (mm)',
        kappe_plate_dim: 'Plate (mm)',
        kappe_fastener_no_plate: 'Festemiddel — ingen platemål',
        kappe_settings_kerf: 'Bladbredde (mm)',
        kappe_settings_plate: 'Standard plate (mm)',
        kappe_stift_add: '+ Legg til stift',
        kappe_fastener_add: '+ Legg til festemiddel',
        kappe_stift_pick: 'Velg stift-størrelse',
        kappe_product_placeholder: 'Velg produkt',
        kappe_clear_product: 'Nullstill',
        kappe_save_success: 'Kappeskjema lagret!',
        kappe_no_saved: 'Ingen lagrede kappeskjema',
        kappe_validation_no_lines: 'Du må legge til minst én kappelinje',
        kappe_validation_no_stift: 'Du må legge til minst ett festemiddel',
        settings_kappe_products: 'Kappeskjema',
        kappe_settings_new_product: 'Nytt produkt',
        kappe_settings_new_product_placeholder: 'f.eks. Fireprotect',
        kappe_settings_new_stift_placeholder: 'f.eks. 22',
        kappe_settings_section_products: 'Produkter',
        kappe_settings_product_name: 'Produkt',
        kappe_settings_product_type: 'Type',
        kappe_product_type_isolasjon: 'Isolasjon',
        kappe_product_type_festemiddel: 'Festemiddel',
        kappe_settings_units: 'Enheter',
        kappe_settings_units_placeholder: 'meter, pakker',
        kappe_settings_brands: 'Merker',
        kappe_settings_dimensions: 'Dimensjoner – iso/festemiddel',
        kappe_settings_isolation_dimensions: 'Isolasjon-dimensjoner',
        kappe_settings_fastener_dimensions: 'Festemiddel-dimensjoner',
        kappe_settings_plates: 'Plater (mm)',
        kappe_settings_plate_assign_title: 'Tildel produkter',
        kappe_settings_plate_used_by: 'Brukes av:',
        kappe_settings_plate_default: 'Default',
        kappe_settings_plate_no_products: 'Ingen tildelte produkter — brukes som fallback',
        kappe_settings_new_brand_placeholder: 'f.eks. Fireprotect',
        settings_kappe_req_content: 'Innhold',
        kappe_settings_no_products: 'Ingen produkter ennå',
        kappe_settings_no_dimensions: 'Ingen dimensjoner — legg til en',
        kappe_settings_new_dimension: 'Legg til',
        kappe_settings_new_dimension_placeholder: 'f.eks. 50',
        kappe_settings_dimension_required: 'Du må fylle inn dimensjon',
        kappe_settings_dimension_duplicate: 'Dimensjonen finnes allerede for dette merket',
        kappe_settings_no_stift: 'Ingen stift-størrelser ennå',
        kappe_settings_name_required: 'Du må fylle inn produktnavn',
        kappe_settings_stift_required: 'Du må fylle inn stift-størrelse',
        kappe_settings_duplicate: 'Oppføringen finnes allerede',
        kappe_settings_edit_name: 'Rediger produktnavn:',
        kappe_settings_edit_stift: 'Rediger stift-størrelse:',
        kappe_settings_remove_confirm: 'Fjern',
        validation_required_field: 'Dette feltet er påkrevd:',

        // Bil (Vehicle inventory)
        toolbar_bil: 'Bil',
        bil_title: 'Bilbeholdning',
        bil_add_pafylling: '+ Servicebil',
        bil_history_title: 'Servicebil',
        useful_links_title: 'Nyttige linker',
        apps_title: 'Apper',
        bil_pafylling_saved: 'Påfylling registrert!',
        bil_delete_pafylling_confirm: 'Slett denne påfyllingen?',
        bil_history_pafylling: 'Inntak',
        bil_history_uttak: 'Uttak',
        bil_no_history: 'Ingen historikk ennå',
        bil_show_more: 'Vis mer ({0} til)',
        bil_show_less: 'Vis mindre',

        // Calculator
        toolbar_calc: 'Verktøy',
        calc_title: 'Kalkulator',
        calc_multicollar_desc: 'Rørdiameter → segmenter',
        calc_pipe_diameter: 'Rørdiameter (mm)',
        calc_segments: 'Segmenter',
        calc_per_roll: 'Per rull',
        calc_reference_table: 'Referansetabell',
        calc_too_large: 'Diameter over 80mm — se produsentens tabell',
        calc_too_small: 'Diameter under 16mm — se produsentens tabell',
        calc_circumference: 'Omkrets',
        calc_cut_length: 'kapplengde',
        calc_cut_length_short: 'Kapp',

        // Brannpakning
        calc_bp_title: 'Brannpakning',
        calc_bp_desc: 'Beregn lengde i meter',
        calc_bp_pipe: 'Rør',
        calc_bp_pipes: 'Antall',
        calc_bp_rounds: 'Runder',
        calc_bp_add_pipe: 'Legg til rør',
        calc_bp_total: 'Totalt',

        // Lysåpning calculator
        calc_la_title: 'Lysåpning',
        calc_la_desc: 'Beregn lysåpning i utsparing',
        calc_la_add_pipe: 'Legg til rør',
        calc_la_result: 'Lysåpning',

        // Brannplate calculator
        calc_plate_title: 'Brannplate',
        calc_plate_desc: 'Beregn antall brannplater',
        calc_gpg_title: 'GPG stein',
        calc_gpg_desc: 'Antall stein og esker',
        calc_iso_title: 'Isolering stift',
        calc_iso_desc: 'Stift/skrue-plassering på plate',
        iso_profile: 'Profil',
        iso_profile_solid: 'HUP (solid)',
        iso_profile_open: 'I/U-profil (åpen)',
        profile_info_title: 'Profiltyper',
        profile_info_solid: 'HUP (solid) – c/c 300, kant 75 mm',
        profile_info_open: 'I/U-profil (åpen) – c/c 300, kant 10 mm',
        profile_info_angle: 'VINKEL',
        iso_method: 'Feste',
        iso_width: 'Bredde (mm)',
        iso_height: 'Høyde (mm)',
        iso_pins: 'Sveisepinner',
        iso_screws: 'Skruer',
        iso_beam: 'Bjelke (I-profil)',
        iso_column: 'Søyle (I-profil)',
        iso_pins_label: 'sveisepinner',
        iso_screws_label: 'skruer',
        iso_edge: 'Kantavstand',
        iso_enter_dims: 'Skriv inn bredde og høyde',
        iso_steg_zone: 'Steg — ingen stifter',
        iso_thickness: 'Tykkelse',
        iso_custom: 'Egendefinert',
        iso_max_cc: 'Maks c/c',
        iso_max_edge: 'Maks kantavstand',
        iso_row_cc: 'Rader',
        iso_screw_edge_note: 'Kantavstand = ½ platetykkelse',

        calc_sw_title: 'Stoppeklokker',
        calc_sw_desc: 'Mål tid på flere bestillinger',
        sw_start: 'Start',
        sw_pause: 'Stopp',
        sw_reset: 'Nullstill',
        sw_copy: 'Kopier',
        sw_copied_toast: 'Kopiert:',
        sw_copy_failed: 'Kunne ikke kopiere',
        sw_add_new: 'Ny stoppeklokke',
        sw_empty: 'Ingen stoppeklokker. Trykk + for å starte en.',
        sw_default_label: 'Bestilling',
        sw_label_placeholder: 'Navn på bestilling',
        sw_delete: 'Slett',
        sw_delete_confirm: 'Slett stoppeklokke',
        sw_reset_confirm: 'Nullstill tiden på stoppeklokke',
        sw_clear_all: 'Slett alle',
        sw_clear_all_confirm: 'Slett alle {n} stoppeklokkene?',
        calc_plate_add: 'Legg til',
        calc_plate_total_area: 'Totalt areal',
        calc_plate_count: 'Brannplater',
        calc_plate_size: 'Platestørrelse (mm)',
    },
    en: {
        // Toolbar
        toolbar_home: 'Home',
        toolbar_save: 'Save',
        toolbar_forms: 'Saved',
        toolbar_export: 'Export',
        toolbar_service: 'Withdrawal',
        toolbar_settings: 'Menu',
        toolbar_timebok: 'Timesheet',
        timebok_title: 'Timesheet',
        timebok_add_day: '+ New day',
        timebok_add_line: '+ Add line',
        timebok_sum_hours: 'Total hours',
        timebok_sum_wage: 'Total wage',
        timebok_sum_travel: 'Travel allowance',
        timebok_sum_days: 'Days logged',
        timebok_summary_title: 'Week summary',
        timebok_summary_title_month: 'Month summary',
        timebok_today: 'Today',
        timebok_no_entries: 'No entries',
        timebok_line_one: 'line',
        timebok_line_many: 'lines',
        timebok_calc_with: 'Calculated with',
        timebok_per_hour: 'per hour',
        timebok_rates_unset: 'Rates not set – fill in under Settings',
        timebok_day_travel: 'Travel allowance',
        timebok_pick_project: 'Select project',
        timebok_pick_type: 'Select code',
        timebok_new_project: '+ Add',
        timebok_new_project_title: 'New project',
        timebok_search_project: 'Search project …',
        timebok_no_project_matches: 'No matches',
        timebok_no_projects: 'No projects yet.',
        timebok_delete_day_confirm: 'Delete this day?',
        timebok_sum_receipts: 'Receipts',
        timebok_sum_total: 'Total',
        timebok_project: 'Project',
        timebok_no_project: 'No project',
        timebok_code_hint: 'Add a code with hours/amount',
        timebok_codes: 'Codes',
        timebok_add_code: '+ Add code',
        timebok_add_project: '+ Add project',
        timebok_receipts: 'Receipts',
        timebok_add_receipt: '+ Add receipt',
        timebok_receipt_label_ph: 'Description',
        timebok_day_totals: 'Day totals',
        timebok_d_hours: 'Hours',
        timebok_d_wage: 'Wage',
        timebok_d_travel: 'Travel',
        timebok_d_receipts: 'Receipts',
        timebok_saved: 'All saved',
        timebok_saving: 'Saving …',
        timebok_menu_today: 'Go to today',
        timebok_menu_settings: 'Settings',
        timebok_sync_projects: 'Import from Projects & storage',
        timebok_projects_added: 'projects added',
        timebok_projects_none_new: 'No new projects',
        settings_timebok: 'Timesheet',
        settings_timebok_timesats: 'Hourly rate',
        settings_timebok_timetypes: 'Time types',
        settings_timebok_brackets: 'Travel allowance (distance)',
        settings_timebok_projects: 'Projects',
        btn_mark_sent: 'Mark sent',
        btn_mark_ferdig: 'Mark approved',
        btn_mark_ikke_godkjent: 'Mark not approved',
        form_mark_btn: 'Mark as',
        mark_sent_confirm: 'Mark this form as sent?',
        mark_ferdig_confirm: 'Mark this form as done (signed)?',
        marked_as_ferdig: 'Form marked as approved!',
        marked_as_ikke_godkjent: 'Form marked as not approved!',

        // Login
        login: 'Log in',
        logout: 'Log out',
        logout_confirm: 'Do you want to log out?',
        logout_success: 'You are now logged out',
        login_success: 'Logged in as ',
        login_failed: 'Login failed: ',
        login_choose_provider: 'Choose login method',
        login_google: 'Sign in with Google',
        login_microsoft: 'Sign in with Microsoft',
        firebase_not_configured: 'Firebase is not configured. Check firebaseConfig in script.js',

        // Loading
        generating_file: 'Generating file...',

        // Sent banner
        sent_banner_text: 'This form has been sent',
        sent_banner_hint: 'Press "Save" to move to saved forms',
        sent_banner_move: 'Move to saved',

        // Mobile form header
        form_subtitle: 'Order Form',
        beta_label: 'Beta',

        // Field labels
        label_ordreseddel_nr: 'Order no.',
        label_uke: 'Week',
        label_montor: 'Technician',
        label_avdeling: 'Department',
        label_oppdragsgiver: 'Client',
        label_kundens_ref: 'Customer ref.',
        label_fakturaadresse: 'Invoice address',
        label_prosjektnr: 'Project no.',
        label_prosjektnavn: 'Project name',
        label_sted: 'Location',
        label_dato: 'Date',
        label_kundens_underskrift: 'Customer signature',
        signature_tap_to_sign: 'Tap to sign',
        signature_not_signed: 'Not signed',
        signature_title: 'Sign here',
        signature_clear: 'Clear signature',
        signature_clear_short: 'Clear',
        signature_confirm: 'Confirm',

        // Sections
        section_work: 'Completed work',
        section_signing: 'Signing',

        // Order cards
        order_description: 'Description',
        order_title: 'Order',
        timer_chip_label: 'Hours logged',
        timer_week_label: 'Hours week',
        timer_week_this: '(this one)',
        timer_week_total: 'Week total',
        timer_day_total: 'Day total',
        timer_week_no_uke: 'Set a week to see the week total.',
        timer_overview_title: 'This order form',
        timer_overview_total: 'Order form total',
        timer_overview_empty: 'No orders yet',
        timer_overview_other: 'Other',
        timer_overview_no_hours: 'No hours logged',
        order_materials_label: 'Materials',
        order_add_material: 'Materials',
        order_edit_material: 'Edit materials',
        material_isolation: 'Insulation',
        material_kappe: 'Insulation',
        order_days: 'Work hours',
        order_skip_materialer: 'No materials for this entry',
        order_skipped_materialer: 'No materials',
        order_skip_arbeidstid: 'No work hours for this entry',
        order_skipped_arbeidstid: 'No work hours',
        btn_undo: 'Undo',
        order_merknad: 'Note',
        order_merknad_placeholder: 'Optional note...',
        order_plan: 'Floor plan',
        order_plan_placeholder: 'Floor(s)...',
        order_add: '+ Add order',
        order_delete_confirm: 'Delete this order?',
        picker_delete_confirm: 'Delete this row?',

        // Material placeholders
        placeholder_material: 'Material',
        placeholder_quantity: 'Quantity',
        placeholder_unit: 'Unit',

        // Save menu
        save_menu_title: 'Save form',
        save_option: 'Save',
        save_as_template: 'Save as project',

        // Save confirmations
        confirm_save: 'Are you sure you want to save the form?',
        confirm_update: 'This order number already exists. Do you want to update it?',
        confirm_move_to_saved: 'Do you want to move this order form back to saved?',
        save_success: 'Form saved!',
        update_success: 'Form updated!',
        save_error: 'Error saving: ',
        duplicate_in_sent: 'Order no. {0} already exists in sent.',
        btn_save: 'Save',
        btn_update: 'Update',

        // Export menu
        export_title: 'Export as',
        export_only_label: 'Export only',
        export_and_mark_label: 'Mark as sent',
        btn_cancel: 'Cancel',
        btn_clear: 'Clear',
        btn_preview: 'Preview',
        btn_close: 'Close',
        btn_back: 'Back',
        btn_sign: 'Sign',
        btn_done: 'Done',
        btn_signed: 'Signed',
        duplicate_btn: 'Duplicate',
        copy_btn: 'Copy',
        edit_btn: 'Edit',
        delete_btn: 'Delete',
        more_actions: 'Actions',
        export_pdf_error: 'Error generating PDF: ',
        export_png_error: 'Error generating PNG: ',
        btn_share: 'Share',
        share_error: 'Error sharing: ',
        share_ready_prompt: 'File is ready. Tap Share to open the share menu.',
        share_not_supported: 'Sharing is not supported in this browser. Use Chrome or a mobile browser.',
        export_download: 'Download',
        btn_select: 'Select',
        btn_download: 'Download',
        btn_export_ellipsis: 'Export…',
        btn_select_all: 'Select all',
        btn_deselect_all: 'Clear all',
        bulk_count_suffix: 'selected',
        bulk_mark_as: 'Mark as:',
        bulk_mark_btn: 'Mark as',
        status_lagret: 'Saved',
        status_sendt: 'Sent',
        status_ferdig: 'Approved',
        status_ikke_godkjent: 'Not approved',
        bulk_mark_confirm: 'Set {0} forms to "{1}"?',
        bulk_marked: '{0} forms set to "{1}"',
        select_mode_title: 'Select forms',
        bulk_export_title: 'Export selected',
        bulk_mark_sent_label: 'Mark all as done',
        bulk_section_combined_pdf: 'Combined PDF (1 file)',
        bulk_section_separate_pdf: 'Separate PDF files',
        bulk_section_separate_png: 'Separate PNG files',
        bulk_combine_pdf_label: 'Combine all PDFs into one file',

        // Hent modal
        modal_load_title: 'Forms',
        tab_own: 'Order form',
        search_placeholder: 'Search order/project no. or project name...',
        search_template_placeholder: 'Search project...',
        loading: 'Loading...',
        no_saved_forms: 'No saved forms',
        no_templates: 'No projects',
        load_more: 'Load more',

        // List items
        no_name: 'Untitled',

        // Form actions
        delete_confirm: 'Are you sure you want to delete this form?',
        delete_sent_confirm: 'Are you sure you want to permanently delete this form?',
        move_to_saved_confirm: 'Do you want to move this form to saved?',
        move_to_saved_success: 'Form moved to saved!',
        marked_as_sent: 'Form marked as sent!',
        btn_ferdig: 'Mark as done',
        btn_move: 'Move',
        duplicate_confirm: 'Do you want to duplicate this form?',
        duplicated_success: 'Form duplicated — remember to save!',
        copied_to_clipboard: 'Copied!',

        // New form
        new_form_confirm: 'Start a new form? Unsaved changes will be lost.',
        btn_start_new: 'Start new',
        unsaved_warning: 'You have unsaved changes. Continue?',
        btn_continue: 'Continue',

        // Templates (a "template" in this app = a saved project)
        template_modal_title: 'Choose project',
        template_section_title: 'Projects',
        template_new_form: 'Own form',
        template_blank_form: '+ Order form',
        template_save_success: 'Project saved!',
        template_duplicated: 'Project duplicated — edit and save!',
        template_update_success: 'Project updated!',
        template_exists: 'A project with name "{0}" already exists. Do you want to update it?',
        template_name_required: 'You must fill in the project name to save the project',
        template_save_error: 'Error saving project: ',
        template_delete_confirm: 'Are you sure you want to delete this project?',

        // Settings
        settings_title: 'Settings',
        settings_ordrenr: 'Order numbers',
        settings_defaults: 'Autofill',
        settings_min_info: 'My info',
        settings_min_info_navn: 'Name',
        settings_min_info_fornavn: 'First name',
        settings_min_info_etternavn: 'Last name',
        signature_rotate_device: 'Rotate your device to landscape',
        settings_min_info_mobil: 'Mobile',
        settings_min_info_epost: 'Email',
        settings_min_info_section_personalia: 'Personal info',
        settings_min_info_section_defaults: 'Default values',
        settings_min_info_default_leveringsadresse: 'Default delivery address (cut form)',
        settings_min_info_uke_hint: 'Set to current week number',
        settings_min_info_dato_hint: 'Set to today\'s date',
        settings_section_autofyll: 'Autofill',
        settings_section_required: 'Required fields',
        settings_section_skjemaer: 'Forms',
        settings_section_global: 'General',
        settings_fields: 'Field settings',
        settings_new_template: '+ New project',
        settings_edit_template: 'Edit project',
        settings_template_deactivate: 'Deactivate',
        settings_template_activate: 'Activate',
        settings_template_inactive: '(deactivated)',
        no_templates_settings: 'No projects',
        template_updated: 'Project updated!',
        settings_language: 'Language',
        settings_saved: 'Settings saved!',
        settings_add_range: 'Add at least one number range.',
        settings_range_error: '"From" must be less than or equal to "To".',
        settings_range_overlap: 'The range overlaps with an existing number range.',
        settings_range_added: 'Number range added!',
        settings_range_remove: 'Remove number range {0} – {1}?',
        settings_no_ranges: 'No number ranges added',
        settings_used: 'Used: {0} of {1}',
        settings_next: 'Next: {0}',
        settings_all_used: 'All used!',
        ordrenr_remaining: '{0} left',
        ordrenr_remaining_empty: 'Out of numbers – ask your manager for more',
        settings_my_numbers: 'My numbers',
        settings_given_away: 'Given away',
        settings_given_away_count: 'Given away: {0}',
        settings_give_btn: 'Give away',
        settings_give_added: 'Numbers marked as given away!',
        settings_give_remove: 'Get back "{0}"?',
        settings_give_not_in_range: 'Numbers must be within a registered number range.',
        settings_give_overlap: 'Overlaps with numbers already given away.',
        settings_give_already_used: 'Number {0} is already used in an order form.',
        settings_defaults_saved: 'Default values saved!',
        settings_values_header: 'Values',
        settings_autofill_header: 'Auto-fill',
        placeholder_from: 'From',
        placeholder_to: 'To',
        btn_save_settings: 'Save',
        btn_add: 'Add',

        // Plan settings
        settings_plans: 'Floor levels',
        settings_plan_add: '+ Add floor',
        settings_plan_placeholder: 'Floor name...',
        settings_plan_exists: 'This floor already exists',
        settings_plan_remove: 'Remove "{0}"?',
        settings_plan_edit_title: 'Edit floor name:',
        settings_no_plans: 'No floors added',
        plan_picker_title: 'Select floor',

        // Materials & units settings
        settings_materials: 'Materials',
        settings_materials_list: 'Materials',
        settings_units_list: 'Units',
        material_type_standard: 'Standard',
        material_type_mansjett: 'Collar',
        material_type_brannpakning: 'Fire seal',
        material_type_kabelhylse: 'Cable sleeve',
        material_type_standard_desc: 'Standard — quantity + unit',
        material_type_mansjett_desc: 'Collar — width/Ø, height',
        material_type_brannpakning_desc: 'Fire seal — width/Ø, height, rounds',
        material_type_kabelhylse_desc: 'Cable sleeve — width/Ø, height, depth',
        placeholder_new_material: 'New material',
        placeholder_new_material_required: 'New material *',
        placeholder_new_unit: 'New unit',
        placeholder_gate: 'Street address',
        placeholder_postnr: 'Zip',
        placeholder_postnr_poststed: 'Zip / City',
        placeholder_poststed: 'City',
        placeholder_fakturaadresse: 'Tap to fill in',
        settings_material_added: 'Material added!',
        settings_unit_added: 'Unit added!',
        settings_material_exists: 'This material already exists.',
        settings_unit_exists: 'This unit already exists.',
        settings_material_remove: 'Remove "{0}"?',
        settings_no_materials: 'No materials added',
        settings_no_units: 'No units added',
        picker_custom: 'Custom',
        picker_add: 'Add',
        picker_ok: 'Ok',
        picker_incomplete: '{0} is missing quantity or unit.',
        picker_search_placeholder: 'Search or add material...',
        settings_spec_toggle: 'Needs dimensions (diameter/size)',
        settings_lm_toggle: 'Calculate running meters',
        settings_default_unit: 'Default unit',
        dim_popup_diameter_placeholder: 'Diameter (mm)',
        dim_popup_width_placeholder: 'Width / Diameter (mm)',
        dim_popup_height_placeholder: 'Height (mm) — optional',
        dim_popup_depth_placeholder: 'Depth (mm)',
        dim_popup_generic_placeholder: 'Width / Diameter (mm)',
        dim_popup_length_placeholder: 'Length (mm) \u2014 optional',
        dim_popup_rounds_placeholder: 'Rounds',
        dim_popup_title_diameter: 'diameter (mm)',
        dim_popup_title_dimensions: 'dimensions (mm)',
        dim_invalid_diameter: 'Please enter a valid measurement',
        material_exists: 'Material already exists',

        // Required fields settings
        settings_required: 'Save & export requirements',
        settings_tpl_required: 'Required fields',
        settings_req_save: 'Save / Export',
        settings_req_template: 'Project',
        settings_req_beskrivelse: 'Description (at least 1 order)',
        settings_req_etasjer: 'Floors',
        validation_kundens_ref: 'Customer ref.',
        validation_fakturaadresse: 'Invoice address',
        validation_signatur: 'Customer signature',

        // Language page
        lang_norwegian: 'Norsk',
        lang_english: 'English',

        // Validation
        required_field: 'You must fill in {0}',
        validation_day_missing_etasje: '{0} is missing floor. When a day has hours, floor must also be set.',
        validation_day_missing_timer: '{0} is missing hours. When a day has floor, hours must also be set.',
        validation_etasje_required: 'Add at least one floor when hours are logged.',
        required_order: 'You must add at least one order',
        required_description: 'Description missing for order {0}',
        validation_ordreseddel_nr: 'Order no.',
        validation_dato: 'Date',
        validation_oppdragsgiver: 'Client',
        validation_prosjektnr: 'Project no.',
        validation_prosjektnavn: 'Project name',
        validation_montor: 'Technician',
        validation_avdeling: 'Department',
        validation_sted: 'Location',
        validation_signering_dato: 'Signing date',

        // Confirm modal defaults
        confirm_default: 'Are you sure?',
        btn_remove: 'Remove',

        form_title: 'Order form',

        // Desktop export labels (used in buildDesktopWorkLines)
        export_materials: 'Materials:',
        export_hours: 'Hours:',
        export_hours_unit: 'hours',
        export_total: 'Total:',

        // Service (Warehouse withdrawal — uttak mode in Servicebil)
        tab_service: 'Withdrawal',
        service_title: 'Warehouse Withdrawal Service Vehicles',
        service_new_form: '+ Withdrawal',
        servicebil_title: 'Service vehicle',
        servicebil_inntak: 'Intake',
        servicebil_uttak: 'Withdrawal',
        servicebil_inntak_title: 'Materials into vehicle',
        servicebil_inntak_no_materials: 'Add at least one material',
        service_entries_title: 'Projects',
        service_add_entry: '+ Add project',
        service_entry_title: 'Project',
        service_entry_delete_confirm: 'Delete this project?',
        service_save_success: 'Withdrawal saved!',
        service_no_saved: 'No saved withdrawals',
        service_montor_required: 'You must fill in technician',
        service_label_signatur: 'Signature',
        template_pick: 'Select project',
        template_picker_title: 'Projects',
        no_templates: 'No projects',

        // Kappeskjema
        kappe_new_form: '+ Cut form',
        kappe_title: 'Cut form',
        tab_kappe: 'Cut',
        tab_servicebil: 'Service vehicle',
        kappe_section_project: 'Project',
        kappe_section_delivery: 'Delivery address',
        kappe_section_customer: 'Customer & invoicing',
        tpl_levering_same_as_faktura: 'Use invoice address',
        tpl_levering_use_faktura: 'Use invoice address',
        fak_use_fakturaadresse: 'Use invoice address',
        fak_use_leveringsadresse: 'Use delivery address',
        tpl_default_leveringsadresse: 'Default delivery address (cut form)',
        tpl_default_leveringsadresse_none: 'None',
        settings_leveringsadresser: 'Delivery addresses',
        settings_templates_and_addresses: 'Projects & depot',
        settings_prosjekter_section: 'Projects',
        settings_lager_section: 'Depot',
        lager_use: 'Use depot',
        lager_not_set: 'No depot set up. Go to Settings → Projects & depot.',
        prosjekt_leveringsadresse_pick: 'Use project',
        prosjekt_leveringsadresse_pick_title: 'Pick project',
        no_prosjekt_leveringsadresser: 'No projects with delivery address',
        settings_new_leveringsadresse: '+ New address',
        settings_edit_leveringsadresse: 'Edit address',
        settings_leveringsadresse_navn: 'Name',
        no_leveringsadresser: 'No saved delivery addresses',
        leveringsadresse_pick: 'Pick delivery address',
        leveringsadresse_pick_title: 'Pick delivery address',
        confirm_delete_leveringsadresse: 'Delete delivery address?',
        kappe_section_products: 'Cut list',
        kappe_section_staples: 'Staples',
        kappe_section_fasteners: 'Fasteners',
        kappe_label_nr: 'Cut form no.',
        kappe_label_dato: 'Date',
        kappe_label_onsket_leveringsdato: 'Desired delivery date',
        kappe_label_bestiller: 'Ordered by',
        kappe_label_mottaker: 'Recipient',
        kappe_label_veiadresse: 'Street address',
        kappe_label_kontakt: 'Contact',
        kappe_label_tlf: 'Phone',
        kappe_label_pallemerking: 'Pallet marking',
        kappe_col_produkt: 'Product',
        kappe_col_bredde: 'Width',
        kappe_col_lopemeter: 'LM',
        kappe_col_antall: 'Quantity',
        kappe_col_antall_sider: 'Sides',
        kappe_lm_title: 'Running meters',
        kappe_add_lengde: 'Add length',
        kappe_add_rad: 'Add row',
        kappe_lm_empty: 'Add lengths below.',
        kappe_lm_sum: 'Total',
        kappe_lengder_badge: 'lengths',
        kappe_steel: 'Steel',
        kappe_steel_new: 'New steel',
        kappe_add_steel: 'Add steel',
        kappe_maal_title: 'Measurements',
        kappe_col_maal: 'Meas.',
        kappe_add_maal: 'Add measurement',
        kappe_maal_empty: 'Enter one or more measurements.',
        iso_bredde: 'Width',
        iso_add_row: 'Add row',
        iso_lm_per_side: 'LM',
        iso_antall_objekter: 'Quantity',
        iso_sider: 'Sides',
        iso_mode_bredde: 'Pcs',
        iso_mode_plate: 'Plate',
        iso_plate_count: 'Plate count',
        kappe_unit_stk: 'Pcs',
        kappe_unit_eske: 'Box',
        kappe_col_kappelengde: 'Cut length',
        kappe_add_line: '+ Add product',
        kappe_line_title: 'Product',
        kappe_line_delete_confirm: 'Delete this cut line?',
        kappe_steel_delete_confirm: 'Delete this steel and all its lengths?',
        kappe_duplicate_line: 'Duplicate product',
        kappe_add_kapp: 'Add piece',
        iso_add_group: 'Add group',
        iso_add_section: 'Add section',
        iso_group_name_ph: 'Group',
        iso_btn_stk: 'Pc',
        iso_btn_plate: 'Plate',
        iso_btn_section: 'Section',
        iso_length_title: 'LM and quantity',
        iso_length_add: 'add',
        btn_ok: 'OK',
        iso_add_product: 'Add insulation product',
        kappe_add_product: '+ Add group',
        kappe_add_plate_product: '+ Plate line',
        kappe_add_plate: 'Add plate',
        kappe_add_fastener: 'Add fastener',
        fastener_choose_product: 'Choose product',
        fastener_edit: 'Edit fasteners',
        iso_edit_products: 'Edit products',
        fastener_add_dimension: 'Add dimension',
        kappe_add_fast_stk: 'Add pcs',
        kappe_add_fast_eske: 'Add box',
        kappe_pick_product_hint: 'Select a product to add rows',
        kappe_kapp_section: 'Cut',
        kappe_plate_section: 'Whole plates',
        kappe_line_plate_delete_confirm: 'Delete this whole-plate line?',
        kappe_col_merknad: 'Note',
        kappe_plate_length: 'Plate length (mm)',
        kappe_plate_width: 'Plate width (mm)',
        kappe_plate_dim: 'Plate (mm)',
        kappe_fastener_no_plate: 'Fastener — no plate size',
        kappe_settings_kerf: 'Blade width (mm)',
        kappe_settings_plate: 'Default plate (mm)',
        kappe_stift_add: '+ Add staple',
        kappe_fastener_add: '+ Add fastener',
        kappe_stift_pick: 'Pick staple size',
        kappe_product_placeholder: 'Select product',
        kappe_clear_product: 'Reset',
        kappe_save_success: 'Cut form saved!',
        kappe_no_saved: 'No saved cut forms',
        kappe_validation_no_lines: 'You must add at least one cut line',
        kappe_validation_no_stift: 'You must add at least one fastener',
        settings_kappe_products: 'Cut form',
        kappe_settings_new_product: 'New product',
        kappe_settings_new_product_placeholder: 'e.g. Fireprotect',
        kappe_settings_new_stift_placeholder: 'e.g. 22',
        kappe_settings_section_products: 'Products',
        kappe_settings_product_name: 'Product',
        kappe_settings_product_type: 'Type',
        kappe_product_type_isolasjon: 'Insulation',
        kappe_product_type_festemiddel: 'Fastener',
        kappe_settings_units: 'Units',
        kappe_settings_units_placeholder: 'meter, packs',
        kappe_settings_brands: 'Brands',
        kappe_settings_dimensions: 'Dimensions – iso/fastener',
        kappe_settings_isolation_dimensions: 'Insulation dimensions',
        kappe_settings_fastener_dimensions: 'Fastener dimensions',
        kappe_settings_plates: 'Plates (mm)',
        kappe_settings_plate_assign_title: 'Assign products',
        kappe_settings_plate_used_by: 'Used by:',
        kappe_settings_plate_default: 'Default',
        kappe_settings_plate_no_products: 'No assigned products — used as fallback',
        kappe_settings_new_brand_placeholder: 'e.g. Fireprotect',
        settings_kappe_req_content: 'Content',
        kappe_settings_no_products: 'No products yet',
        kappe_settings_no_dimensions: 'No dimensions — add one',
        kappe_settings_new_dimension: 'Add',
        kappe_settings_new_dimension_placeholder: 'e.g. 50',
        kappe_settings_dimension_required: 'Dimension is required',
        kappe_settings_dimension_duplicate: 'Dimension already exists for this brand',
        kappe_settings_no_stift: 'No staple sizes yet',
        kappe_settings_name_required: 'Product name is required',
        kappe_settings_stift_required: 'Staple size is required',
        kappe_settings_duplicate: 'Entry already exists',
        kappe_settings_edit_name: 'Edit product name:',
        kappe_settings_edit_stift: 'Edit staple size:',
        kappe_settings_remove_confirm: 'Remove',
        validation_required_field: 'This field is required:',

        // Bil (Vehicle inventory)
        toolbar_bil: 'Vehicle',
        bil_title: 'Vehicle Inventory',
        bil_add_pafylling: '+ Service vehicle',
        bil_history_title: 'Service vehicle',
        useful_links_title: 'Useful links',
        apps_title: 'Apps',
        bil_pafylling_saved: 'Stock added!',
        bil_delete_pafylling_confirm: 'Delete this stock entry?',
        bil_history_pafylling: 'Intake',
        bil_history_uttak: 'Withdrawal',
        bil_no_history: 'No history yet',
        bil_show_more: 'Show more ({0} more)',
        bil_show_less: 'Show less',

        // Calculator
        toolbar_calc: 'Tools',
        calc_title: 'Calculator',
        calc_multicollar_desc: 'Pipe diameter → segments',
        calc_pipe_diameter: 'Pipe diameter (mm)',
        calc_segments: 'Segments',
        calc_per_roll: 'Per roll',
        calc_reference_table: 'Reference table',
        calc_too_large: 'Diameter over 80mm — see manufacturer table',
        calc_too_small: 'Diameter under 16mm — see manufacturer table',
        calc_circumference: 'Circumference',
        calc_cut_length: 'cut length',
        calc_cut_length_short: 'Cut',

        // Brannpakning
        calc_bp_title: 'Fire seal',
        calc_bp_desc: 'Calculate length in meters',
        calc_bp_pipe: 'Pipe',
        calc_bp_pipes: 'Qty',
        calc_bp_rounds: 'Rounds',
        calc_bp_add_pipe: 'Add pipe',
        calc_bp_total: 'Total',

        // Light opening calculator
        calc_la_title: 'Light opening',
        calc_la_desc: 'Calculate light opening in penetration',
        calc_la_add_pipe: 'Add pipe',
        calc_la_result: 'Light opening',

        // Fire board calculator
        calc_plate_title: 'Fire board',
        calc_plate_desc: 'Calculate fire boards needed',
        calc_gpg_title: 'GPG stone',
        calc_gpg_desc: 'Number of stones and boxes',
        calc_iso_title: 'Insulation pins',
        calc_iso_desc: 'Pin/screw placement on plate',
        iso_profile: 'Profile',
        iso_profile_solid: 'HSS (solid)',
        iso_profile_open: 'I/U-profile (open)',
        profile_info_title: 'Profile types',
        profile_info_solid: 'HSS (solid) – c/c 300, edge 75 mm',
        profile_info_open: 'I/U-profile (open) – c/c 300, edge 10 mm',
        profile_info_angle: 'ANGLE',
        iso_method: 'Fastening',
        iso_width: 'Width (mm)',
        iso_height: 'Height (mm)',
        iso_pins: 'Welding pins',
        iso_screws: 'Screws',
        iso_beam: 'Beam (I-profile)',
        iso_column: 'Column (I-profile)',
        iso_pins_label: 'welding pins',
        iso_screws_label: 'screws',
        iso_edge: 'Edge distance',
        iso_enter_dims: 'Enter width and height',
        iso_steg_zone: 'Web — no pins',
        iso_thickness: 'Thickness',
        iso_custom: 'Custom',
        iso_max_cc: 'Max c/c',
        iso_max_edge: 'Max edge distance',
        iso_row_cc: 'Rows',
        iso_screw_edge_note: 'Edge distance = ½ plate thickness',

        calc_sw_title: 'Stopwatches',
        calc_sw_desc: 'Track time on multiple jobs',
        sw_start: 'Start',
        sw_pause: 'Stop',
        sw_reset: 'Reset',
        sw_copy: 'Copy',
        sw_copied_toast: 'Copied:',
        sw_copy_failed: 'Could not copy',
        sw_add_new: 'New stopwatch',
        sw_empty: 'No stopwatches. Tap + to start one.',
        sw_default_label: 'Job',
        sw_label_placeholder: 'Job name',
        sw_delete: 'Delete',
        sw_delete_confirm: 'Delete stopwatch',
        sw_reset_confirm: 'Reset the time on stopwatch',
        sw_clear_all: 'Delete all',
        sw_clear_all_confirm: 'Delete all {n} stopwatches?',
        calc_plate_add: 'Add row',
        calc_plate_total_area: 'Total area',
        calc_plate_count: 'Fire boards',
        calc_plate_size: 'Board size (mm)',
    }
};
